services:
  - type: web
    name: peanut-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: OLLAMA_HOST
        value: http://127.0.0.1:11434
